spring:
  application:
    name: tix-management
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db-changelog-master.xml
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      '[hibernate.generate_statistics]': false
      '[hibernate.jdbc.batch_size]': 5
      '[hibernate.order_inserts]': true
      '[enable_lazy_load_no_trans]': true
  thymeleaf:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: always
logging:
  pattern:
    console: '[%date{yyyy MM dd HH:mm:ss.SSS} | %-5p | %X{loggedInUser} | %logger{35} | %m%n]'