spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /console
  mail:
    host: smtp
    
mail:
  sender: mcenci@intesigroup.com
  service-fqdn: http://localhost:8080
logging:
  level:
    web: INFO
    '[org.springframework.security]': DEBUG 